[package]
edition = "2018"
name = "frontend"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.16.2"
yew-sse = {git = "https://github.com/liquidnya/yew-sse", features = ["web_sys"]}
anyhow = "*"
