[package]
name = "xtask"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duct = "0.13"
clap = "3.0.0-beta.2"
cargo_metadata = "0.14"
color-eyre = "0.5"